<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class EffortTestRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    
    public function rules()
    {
       return [
             'patient_id'  => 'required|integer',
             'Fecha_TMT'    => 'required|date',
             'Medicamento1_TMT'  => 'nullable|max:100',
            'Dosis1_TMT'         => 'nullable|max:100',
            'TiempoUl1_TMT'      => 'nullable|max:15',
            'Medicamento2_TMT'   => 'nullable|max:100',
            'Dosis2_TMT'         => 'nullable|max:100',
            'TiempoUl2_TMT'      => 'nullable|max:15',
            'Medicamento3_TMT'   => 'nullable|max:100',
            'Dosis3_TMT'         => 'nullable|max:100',
            'TiempoUl3_TMT'      => 'nullable|max:15',
            'Medicamento4_TMT'   => 'nullable|max:100',
            'Dosis4_TMT'         => 'nullable|max:100',
            'TiempoUl4_TMT'      => 'nullable|max:15',
            'FC100_TMT'          => 'nullable|integer',
            'FC85_TMT'           => 'nullable|integer',
            'FC75_TMT'           => 'nullable|integer',
            'Bruce_TMT'          => 'nullable|integer',
            'Naugthon_TMT'       => 'nullable|integer',
            'Otro_TMT'           => 'nullable|integer',
            'RepPAS_TMT'         => 'nullable|integer',
            'CalPAS_TMT'         => 'nullable|integer',
            'EstaIPAS_TMT'       => 'nullable|integer',
            'EstaIIPAS_TMT'      => 'nullable|integer',
            'EstaIIIPAS_TMT'     => 'nullable|integer',
            'EstaIVPAS_TMT'      => 'nullable|integer',
            'EstaVPAS_TMT'  => 'nullable|integer',
            'Recup1PAS_TMT'  => 'nullable|integer',
            'Recup2PAS_TMT'  => 'nullable|integer',
            'Recup3PAS_TMT'  => 'nullable|integer',
            'Recup4PAS_TMT'  => 'nullable|integer',
            'Recup8PAS_TMT'  => 'nullable|integer',
            'Recup10PAS_TMT'  => 'nullable|integer',
            'RepPAD_TMT'  => 'nullable|integer',
            'CalPAD_TMT'  => 'nullable|integer',
            'EstaIPAD_TMT'  => 'nullable|integer',
            'EstaIIPAD_TMT'  => 'nullable|integer',
            'EstaIIIPAD_TMT'  => 'nullable|integer',
            'EstaIVPAD_TMT'  => 'nullable|integer',
            'EstaVPAD_TMT'  => 'nullable|integer',
            'Recup1PAD_TMT'  => 'nullable|integer',
            'Recup2PAD_TMT'  => 'nullable|integer',
            'Recup3PAD_TMT'  => 'nullable|integer',
            'Recup4PAD_TMT'  => 'nullable|integer',
            'Recup8PAD_TMT'  => 'nullable|integer',
            'Recup10PAD_TMT'  => 'nullable|integer',
            'RepFC_TMT'  => 'nullable|integer',
            'CalFC_TMT'  => 'nullable|integer',
            'EstaIFC_TMT'  => 'nullable|integer',
            'EstaIIFC_TMT'  => 'nullable|integer',
            'EstaIIIFC_TMT'  => 'nullable|integer',
            'EstaIVFC_TMT'  => 'nullable|integer',
            'EstaVFC_TMT'  => 'nullable|integer',
            'Recup1FC_TMT'  => 'nullable|integer',
            'Recup2FC_TMT'  => 'nullable|integer',
            'Recup3FC_TMT'  => 'nullable|integer',
            'Recup4FC_TMT'  => 'nullable|integer',
            'Recup8FC_TMT'  => 'nullable|integer',
            'Recup10FC_TMT'  => 'nullable|integer',
            'RepInfSTT_TMT'  => 'nullable|integer',
            'CalInfSTT_TMT'  => 'nullable|integer',
            'EstaIInfSTT_TMT'  => 'nullable|integer',
            'EstaIIInfSTT_TMT'  => 'nullable|integer',
            'EstaIIIInfSTT_TMT'  => 'nullable|integer',
            'EstaIVInfSTT_TMT'  => 'nullable|integer',
            'EstaVInfSTT_TMT'  => 'nullable|integer',
            'Recup1InfSTT_TMT'  => 'nullable|integer',
            'Recup2InfSTT_TMT'  => 'nullable|integer',
            'Recup3InfSTT_TMT'  => 'nullable|integer',
            'Recup4InfSTT_TMT'  => 'nullable|integer',
            'Recup8InfSTT_TMT'  => 'nullable|integer',
            'Recup10InfSTT_TMT'  => 'nullable|integer',
            'RepAngor_TMT'  => 'nullable|integer',
            'CalAngor_TMT'  => 'nullable|integer',
            'EstaIAngor_TMT'  => 'nullable|integer',
            'EstaIIAngor_TMT'    => 'nullable|integer',
            'EstaIIIAngor_TMT'   => 'nullable|integer',
            'EstaIVAngor_TMT'    => 'nullable|integer',
            'EstaVAngor_TMT'     => 'nullable|integer',
            'Recup1Angor_TMT'    => 'nullable|integer',
            'Recup2Angor_TMT'    => 'nullable|integer',
            'Recup3Angor_TMT'    => 'nullable|integer',
            'Recup4Angor_TMT'    => 'nullable|integer',
            'Recup8Angor_TMT'    => 'nullable|integer',
            'Recup10Angor_TMT'   => 'nullable|integer',
            'RepArritVent_TMT'   => 'nullable|integer',
            'CalArritVent_TMT'   => 'nullable|integer',
            'EstaIArritVent_TMT'   => 'nullable|integer',
            'EstaIIArritVent_TMT'  => 'nullable|integer',
            'EstaIIIArritVent_TMT' => 'nullable|integer',
            'EstaIVArritVent_TMT'  => 'nullable|integer',
            'EstaVArritVent_TMT'   => 'nullable|integer',
            'Recup1ArritVent_TMT'  => 'nullable|integer',
            'Recup2ArritVent_TMT'  => 'nullable|integer',
            'Recup3ArritVent_TMT'  => 'nullable|integer',
            'Recup4ArritVent_TMT'  => 'nullable|integer',
            'Recup8ArritVent_TMT'  => 'nullable|integer',
            'Recup10ArritVent_TMT' => 'nullable|integer',
            'RepArritSupV_TMT'     => 'nullable|integer',
            'CalArritSupV_TMT'     => 'nullable|integer',
            'EstaIArritSupV_TMT'   => 'nullable|integer',
            'EstaIIArritSupV_TMT'  => 'nullable|integer',
            'EstaIIIArritSupV_TMT' => 'nullable|integer',
            'EstaIVArritSupV_TMT'  => 'nullable|integer',
            'EstaVArritSupV_TMT'   => 'nullable|integer',
            'Recup1ArritSupV_TMT'  => 'nullable|integer',
            'Recup2ArritSupV_TMT'  => 'nullable|integer',
            'Recup3ArritSupV_TMT'  => 'nullable|integer',
            'Recup4ArritSupV_TMT'  => 'nullable|integer',
            'Recup8ArritSupV_TMT'  => 'nullable|integer',
            'Recup10ArritSupV_TMT' => 'nullable|integer',
            'ArritVent_Mono_TMT'   => 'nullable|integer',
            'ArritVent_Polimo_TMT' => 'nullable|integer',
            'ArritVent_Bige_TMT'   => 'nullable|integer',
            'ArritVent_Pareadas_TMT'  => 'nullable|integer',
            'ArritVent_RT_TMT'     => 'nullable|integer',
            'ArritVent_TV_TMT'     => 'nullable|integer',
            'RazonDet_SolPac_TMT'  => 'nullable|integer',
            'RazonDet_Arrit_TMT'   => 'nullable|integer',
            'RazonDet_HTA_TMT'     => 'nullable|integer',
            'RazonDet_Isq_TMT'     => 'nullable|integer',
            'RazonDet_85FCmax_TMT'  => 'nullable|integer',
            'Isquemia_TMT'  => 'nullable|integer',
            'Arritmia_TMT'  => 'nullable|integer',
            'HTA_TMT'      => 'nullable|integer',
            'MetsAlc_TMT'  => 'nullable|integer',
            'TtoInd1'      => 'nullable|max:100',
            'DosisTtoind1_TMT'  => 'nullable|integer',
            'TtoInd2'      => 'nullable|max:100',
            'DosisTtoind2_TMT'  => 'nullable|integer',
            'TtoInd3'     => 'nullable|max:100',
            'DosisTtoind3_TMT'  => 'nullable|integer',
            'TtoInd4'     => 'nullable|max:100',
            'DosisTtoind4_TMT'  => 'nullable|integer',
            'Doctor_TMT'  => 'nullable|max:100',
            'Fecha_TMT2'  => 'nullable|date'
        ];
    }
}
