<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class CardiovascularV1 extends Model
{
    use SoftDeletes;
    protected $table     ="cardiovascular_v1";
    protected $fillable  = ['patient_id',
                              'user_id',
                              'EC_GradoInstruccion',
                              'EC_Direccion',
                              'EC_Telefono',
                              'EC_FechaEvaluacion',
                              'EC_LugarEval',
                              'EC_NombreEvaluador',
                              'EC_EnfCardiaca',
                              'EC_Infarto',
                              'EC_ICC',
                              'EC_Angina',
                              'EC_Arritmias',
                              'EC_CardioCong',
                              'EC_SoplosCard',
                              'EC_Chagas',
                              'EC_Marcapaso',
                              'EC_Revascula_Coronaria',
                              'EC_OtrasEnfCard',
                              'EC_HTA',
                              'EC_HTAtrt',
                              'EC_Diabetes',
                              'EC_Epilpsia',
                              'EC_Enf_Tiroidea',
                              'EC_Cancer',
                              'EC_TCE',
                              'EC_Enf_renal',
                              'EC_EnfHepatica',
                              'EC_SifilisSIDA',
                              'EC_Enf_SNC',
                              'EC_Dislipidemias',
                              'EC_Enf_vasculares',
                              'EC_Traumatismo_Toracico',
                              'EC_Tumor',
                              'EC_Enf_pulmonar',
                              'EC_PerdidaVisAud',
                              'EC_Tabaquismo',
                              'EC_Tiempo_fumando',
                              'EC_Cajas',
                              'EC_Colagenopatias',
                              'EC_OtrasEnfoQx',
                              'EC_EC_Hospt10a',
                              'EC_RetrasoMental',
                              'EC_Alcohol',
                              'EC_Inf_Padre',
                              'EC_Ang_Padre',
                              'EC_HTA_Padre',
                              'EC_ACV_Padre',
                              'EC_ICC_Padre',
                              'EC_MuertSub_Padre',
                              'EC_DM_Padre',
                              'EC_Cancer_Padre',
                              'EC_Inf_Madre',
                              'EC_Ang_Madre',
                              'EC_HTA_Madre',
                              'EC_ACV_Madre',
                              'EC_ICC_Madre',
                              'EC_Muert_Madre',
                              'EC_DM_Madre',
                              'EC_Cancer_Madre',
                              'EC_Inf_Hermanos',
                              'EC_Ang_Hermanos',
                              'EC_HTA_Hermanos',
                              'EC_ACV_Hermanos',
                              'EC_ICC_Hermanos',
                              'EC_MuertSub_Hermanos',
                              'EC_DM_Hermanos',
                              'EC_Cancer_Hermanos',
                              'EC_Inf_Hijos',
                              'EC_Ang_Hijos',
                              'EC_HTA_Hijos',
                              'EC_ACV_Hijos',
                              'EC_ICC_Hijos',
                              'EC_MuertSub_Hijos',
                              'EC_DM_Hijos',
                              'EC_Cancer_Hijos',
                              'EC_Inf_AbuePater',
                              'EC_Ang_AbuePater',
                              'EC_HTA_AbuePater',
                              'EC_ACV_AbuePater',
                              'EC_ICC_AbuePater',
                              'EC_MuertSub_AbuePater',
                              'EC_DM_AbuePater',
                              'EC_Cancer_AbuePater',
                              'EC_Inf_AbueMater',
                              'EC_Ang_AbueMater',
                              'EC_HTA_AbueMater',
                              'EC_ACV_AbueMater',
                              'EC_ICC_AbueMater',
                              'EC_MuertSub_AbueMater',
                              'EC_DM_AbueMater',
                              'EC_Cancer_AbueMater',
                              'EC_Inf_Tio',
                              'EC_Ang_Tio',
                              'EC_HTA_Tio',
                              'EC_ACV_Tio',
                              'EC_ICC_Tio',
                              'EC_MuertSub_Tio',
                              'EC_DM_Tio',
                              'EC_Cancer_Tio',
                              'EC_Ang_Est_pas',
                              'EC_Ang_Est_prese',
                              'EC_Ang_estable',
                              'EC_Ang_Ines_pas',
                              'EC_Ang_Ines_prese',
                              'EC_Ang_inestable',
                              'EC_Palpi_pasado',
                              'EC_Palpi_presente',
                              'EC_Palpitaciones',
                              'EC_DPN_pasado',
                              'EC_DPN_presente',
                              'EC_DPN',
                              'EC_DisEsf_pasado',
                              'EC_DisEsf_presente',
                              'EC_Disnea_esfuerzo',
                              'EC_Ortopn_pas',
                              'EC_Ortopn_prese',
                              'EC_Ortopnea',
                              'EC_Mareos_pasado',
                              'EC_Mareos_presente',
                              'EC_Mareos',
                              'EC_Sincope_pasado',
                              'EC_Sincope_presente',
                              'EC_Sincope',
                              'EC_EMI_pasado',
                              'EC_EMI_presente',
                              'EC_Edem_MI',
                              'EC_AptoCardio',
                              'EC_SNCyPsi',
                              'EC_Quimio',
                              'EC_AptoGastro',
                              'EC_AccionLocal',
                              'EC_OtrosMed',
                              'EC_Peso',
                              'EC_Talla',
                              'EC_Ccintura',
                              'EC_Ccadera',
                              'EC_PligueCut',
                              'EC_SC',
                              'EC_FC',
                              'EC_FR',
                              'EC_PAS_sent',
                              'EC_PAD_sent',
                              'EC_PAS_pie',
                              'EC_PAD_pie',
                              'EC_PP_sentado',
                              'EC_Disnea',
                              'EC_ClaudInterm',
                              'EC_AnorLatiPunt',
                              'EC_RitmoCnormal',
                              'EC_soplo_cardiaco',
                              'EC_RuidoBajaTona',
                              'EC_SoploCarotideo',
                              'EC_FrotePericardico',
                              'EC_AuscPulnormal',
                              'EC_Hepatomegalia',
                              'EC_ReflujoHepa',
                              'EC_EMI',
                              'EC_Varicosidades',
                              'EC_PulsoNormal',
                              'EC_SoploAbdominal',
                              'EC_Otros',
                              'EC_Sinusal',
                              'EC_NoSinusal',
                              'EC_FA',
                              'EC_FC2',
                              'EC_PR',
                              'EC_QRS',
                              'EC_QT',
                              'EC_AQRS',
                              'EC_supraventiculares',
                              'EC_ventriculares',
                              'EC_1de1',
                              'EC_2de1',
                              'EC_monomorficas',
                              'EC_polimorficas',
                              'EC_bigeminadas',
                              'EC_trigeminada',
                              'EC_dupletas',
                              'EC_derechaincompleto',
                              'EC_derechacompleto',
                              'EC_izquierdaincompleto',
                              'EC_izquierdacompleto',
                              'EC_hemibloqueoAnt',
                              'EC_hemibloqueoPost',
                              'EC_Primer',
                              'EC_mobitz_I',
                              'EC_mobitz_II',
                              'EC_completo',
                              'EC_bradicardia',
                              'EC_flutterAuricular',
                              'EC_taquicardiaSinus',
                              'EC_TPSV',
                              'EC_WPW',
                              'EC_TauricularMultifocal',
                              'EC_AuricularIzq',
                              'EC_AuricularDer',
                              'EC_VentriculoIzq',
                              'EC_VentriculoDer',
                              'EC_IsqSubepi_Inf',
                              'EC_IsqSubepi_Septal',
                              'EC_IsqSubepi_Antsep',
                              'EC_IsqSubepi_Ant',
                              'EC_IsqSubepi_AntExt',
                              'EC_IsqSubend_Inf',
                              'EC_IsqSubend_Septal',
                              'EC_IsqSubend_Antsep',
                              'EC_IsqSubend_Ant',
                              'EC_IsqSubend_AntExt',
                              'EC_LesSubepi_Inf',
                              'EC_LesSubepi_Septal',
                              'EC_LesSubepi_Antsep',
                              'EC_LesSubepi_Ant',
                              'EC_LesSubepi_AntExt',
                              'EC_LesSubend_Inf',
                              'EC_LesSubend_Septal',
                              'EC_LesSubend_Antsep',
                              'EC_LesSubend_Ant',
                              'EC_LesSubend_AntExt',
                              'EC_NecroInf',
                              'EC_NecroSeptal',
                              'EC_NecroAntSept',
                              'EC_NecroAnt',
                              'EC_NecroExt',
                              'EC_NecroPost'
                              ];


    
      protected $dates = ['deleted_at','created_at','updated_at'];

      public function user()
      {
            return $this->belongsTo(User::class,'user_id')->withDefault([
                  'name' => 'N/A',
              ]);
      }

      public function patient() {
            return $this->belongsTo(Patient::class,'patient_id','patient_id')->withDefault([
                  'hist_id' => 0,
                  'cedula' => 0,
                  'first_name' => '',
                  'last_name' => '',
             ]);
      }

    public function scopeSearch($query, $search)
    {

      $query->join('patient as p','p.patient_id','cardiovascular_v1.patient_id');

      if(trim($search)) {
        
        return $query->where('p.hist_id', 'LIKE', "%$search%")
                     ->orWhere(\DB::RAW("CONCAT_WS(' ',p.first_name, p.second_name, p.last_name, p.second_last_name) "), 'LIKE', "%$search%");
      }
      
    }
}
