<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CoreEvaluation extends Model
{
    use SoftDeletes;
	protected $table="core_evaluation";

    protected $fillable = [
                        'patient_id',
						'user_id',
						'Core_Edo_Civil',
						'Core_NdeHijos',
						'Core_Genero',
						'AgeCore',
						'edu_core',
						'lentes',
						'disponib',
						'Core_Vision',
						'sordo',
						'ayuda',
						'laterali',
						'Core_Hemiparesia',
						'DatCore',
						'Core_NdeEvaluacion',
						'Core_Examinador',
						'ori_tiemp2',
						'ori_tiemp4',
						'ori_tiemp5',
						'ori_tiemp1',
						'ori_tiemp3',
						'ori_tiemptot',
						'ori_esp1',
						'ori_esp7',
						'ori_esp4',
						' ori_esp3',
						'ori_esp5',
						'ori_esp2',
						'ori_esptot',
						'orientac',
						'Bpr1',
						'Bpr2',
						'Bpr3',
						'Bpr4',
						'Bpr5',
						'Bpr6',
						'Bpr7',
						'Bpr8',
						'Bpr9',
						'Bpr10',
						'Bpp1',
						'Bpp2',
						'Bpp3',
						'Bpp4',
						'Bpp5',
						'Bpp6',
						'Bpp7',
						'Bpp8',
						'Bpp9',
						'Bpp10',
						'Bentonpar',
						'Bdr1',
						'Bdr2',
						'Bdr3',
						'Bdr4',
						'Bdr5',
						'Bdr6',
						'Bdr7',
						'Bdr8',
						'Bdr9',
						'Bdr10',
						'Bdp1',
						'Bdp2',
						'Bdp3',
						'Bdp4',
						'Bdp5',
						'Bdp6',
						'Bdp7',
						'Bdp8',
						'Bdp9',
						'Bdp10',
						'Bentondif',
						'Core_MATTIS_Igual1',
						'Core_MATTIS_Igual2',
						'Core_MATTIS_Igual3',
						'Core_MATTIS_Igual4',
						'Core_MATTIS_Igual5',
						'Core_MATTIS_Igual6',
						'Core_MATTIS_Igual7',
						'Core_MATTIS_Igual8',
						'Core_MATTIS_Igual_Total',
						'Core_MATTIS_DesIgual1',
						'Core_MATTIS_DesIgual2',
						'Core_MATTIS_DesIgual3',
						'Core_MATTIS_DesIgual4',
						'Core_MATTIS_DesIgual5',
						'Core_MATTIS_DesIgual6',
						'Core_MATTIS_DesIgual7',
						'Core_MATTIS_DesIgual8',
						'Core_MATTIS_DesIgual_Total',
						'Core_MATTIS_Totalscore',
						'Core_PRS1_Memoria',
						'Core_PRS2_Memoria',
						'Core_PRS3_Memoria',
						'Core_PRS4_Memoria',
						'Core_PRS5_Memoria',
						'Core_PRS6_Memoria',
						'Core_PRS7_Memoria',
						'Core_PRS8_Memoria',
						'Core_PRS9_Memoria',
						'Core_PRS10_Memoria',
						'Core_PRS11_Memoria',
						'Core_PRS12_Memoria',
						'Core_MemoriaScore',
						'Core_PRS1_Reco',
						'Core_PRS2_Reco',
						'Core_PRS3_Reco',
						'Core_PRS4_Reco',
						'Core_PRS5_Reco',
						'Core_PRS6_Reco',
						'Core_PRS7_Reco',
						'Core_PRS8_Reco',
						'Core_PRS9_Reco',
						'Core_PRS10_Reco',
						'Core_PRS11_Reco',
						'Core_PRS12_Reco',
						'Core_Reco',
						'Core_TotalPRS',
						'Core_Semenjanzas_Preg1',
						'Core_Semenjanzas_Preg2',
						'Core_Semenjanzas_Preg3',
						'Core_Semenjanzas_Preg4',
						'Core_Semenjanzas_Preg5',
						'Core_Semenjanzas_Preg6',
						'Core_Semenjanzas_Preg7',
						'Core_Semenjanzas_Preg8',
						'Core_Semenjanzas_Preg9',
						'Core_Semenjanzas_Preg10',
						'Core_Semenjanzas_Preg11',
						'Core_Semenjanzas_Preg12',
						'Core_Semenjanzas_Preg13',
						'Core_Semenjanzas_Preg14',
						'Core_Semenjanzas_Totalscore',
						'boston_af1a',
						'boston_af2a',
						'boston_af3a',
						'boston_af4a',
						'boston_af1b',
						'boston_af2b',
						'boston_af3b',
						'boston_af4b',
						'boston_af5a',
						'boston_af5b',
						'boston_af6a',
						'boston_af6b',
						'boston_af',
						'Core_Repeticion_Frases_Sabes',
						'Core_Repeticion_Frases_Tierra',
						'Core_Repeticion_Frases_Trabajo',
						'Core_Repeticion_Frases_decirte',
						'Core_Repeticion_Frases_hazlo',
						'Core_Repeticion_Frases_comedor',
						'Core_Repeticion_Frases_Radio',
						'Core_Repeticion_Frases_Timbre',
						'Core_Repeticion_Frases_Total',
						'rtiempo',
						'racierto',
						'rerror',
						'romis',
						'tmxtpo',
						'tmxacier',
						'tmxerror',
						'tmxomis',
						'Core_PrCanc_Rombo_ULorSI',
						'Core_PrCanc_Rombo_URorSD',
						'Core_PrCanc_Rombo_LLorII',
						'Core_PrCanc_Rombo_LRorID',
						'Core_PrCanc_TMX_ULorSI',
						'Core_PrCanc_TMX_URorSD',
						'Core_PrCanc_TMX_LLorII',
						'Core_PrCanc_TMX_LRorID',
						'rosen1',
						'rosen2',
						'rosen3',
						'rosen4',
						'rosen5',
						'rosenptj',
						'bostonsa',
						'bostonec',
						'bostonef',
						'acptotal',
						'Core_Leng_asoconpal_PC',
						'Core_Leng_asoconpal_P',
						'Core_Leng_asoconpal_Puntaje',
						'Core_Leng_asoconpal_PuntajeLimit',
						'Core_Leng_Cagoria_Puntaje',
						'Core_Leng_Cagoria_Limit',
						'Core_Leng_Animales_Puntaje',
						'Core_Leng_Repeticion_Puntaje',
						'Core_Leng_Repeticion_Limit',
						'Core_Leng_Compresion_Puntaje',
						'Core_Leng_Compresion_Limit',
						'Core_Const_Rosen_Repasados',
						'Core_Const_Rosen_Puntaje',
						'Core_Const_Rosen_Puntaje_Limit',
						'Core_Const_Benton_Puntaje',
						'Core_Const_Benton_Puntaje_Limit',
						'rtiempo2',
						'racierto2',
						'Core_Atenc_Cancel_Rombo_Errores',
						'Core_Atenc_Cancel_Rombo_Omisiones',
						'tmxtpo2',
						'tmxacier2',
						'Core_Atenc_Cancel_TMX_Errores',
						'Core_Atenc_Cancel_TMX_Omisiones',
						'Core_Atenc_Cancel_Rombo_ULorSI',
						'Core_Atenc_Cancel_Rombo_URorSD',
						'Core_Atenc_Cancel_Rombo_LLorII',
						'Core_Atenc_Cancel_Rombo_LRorID',
						'Core_Atenc_Cancel_TMX_ULorSI',
						'Core_Atenc_Cancel_TMX_URorSD',
						'Core_Atenc_Cancel_TMX_LLorII',
						'Core_Atenc_Cancel_TMX_LRorID',
						'memtot',
						'memtot_limit',
						'mlp',
						'mlp_limit',
						'mediata',
						'mediate_limit',
						'reconoc',
						'reconoc_limit',
						'alptot_PB',
						'alptot_PC',
						'alp',
						'crlp_PB',
						'crlp_PC',
						'crlp',
						'Core_Total_Intrusiones',
						'Core_Intrusiones_Diferentes',
						'Core_Palab_recorda_6intentos',
						'bentonm_Puntaje',
						'bentonm_Limit',
						'orientac_Puntaje',
						'orientac_Limit',
						'Core_Razo_abs_sem_PB',
						'Core_Razo_abs_sem_PC',
						'Core_Razo_abs_sem_Edad',
						'Core_Razo_abs_sem_puntaje',
						'Core_Razo_abs_sem_Limit',
						'igual',
						'desigual',
						'igualtot',
						'igualtot_Limit'
						 ];


	protected $dates = ['deleted_at','created_at','updated_at'];

	public function user()
      {
            return $this->belongsTo(User::class,'user_id')->withDefault([
                  'name' => 'N/A',
              ]);
      }

      public function patient() {
            return $this->belongsTo(Patient::class,'patient_id','patient_id')->withDefault([
                  'hist_id' => 0,
                  'cedula' => 0,
                  'first_name' => '',
                  'last_name' => '',
             ]);
      }

    public function scopeSearch($query, $search)
    {

     $query->join('patient as p','p.patient_id','core_evaluation.patient_id');

      if(trim($search)) {
        
        return $query->where('p.hist_id', 'LIKE', "%$search%")
                     ->orWhere(\DB::RAW("CONCAT_WS(' ',p.first_name, p.second_name, p.last_name, p.second_last_name) "), 'LIKE', "%$search%");
      }
      
    }
}
